[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "py-triex"
version = "2.0.7a0"
description = "A tool to generate semi-minimized regular expression alternations."
license = {text = "MIT"}
readme = "README.md"
authors = [
  { name = "lojoja", email = "dev@lojoja.com" }
]
requires-python = ">=3.10,<4"
dependencies = [
  "click==8.*",
  "clickext>=1.0.1,<2"
]
dynamic = ["classifiers"]

[project.urls]
homepage = "https://github.com.com/lojoja/triex"
repository = "https://github.com.com/lojoja/triex"
"Bug Tracker" = "https://github.com/lojoja/triex/issues"

[project.scripts]
triex = "triex.cli:cli"

[tool.poetry]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
packages = [
    {include = "triex"}
]

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pylint = "^3.3.7"
pyright = "^1.1.401"
pytest = "^8.4.0"
pytest-cov = ">=4.1,<7.0"

[tool.black]
include = '\.pyi?$'
line-length = 120
skip-magic-trailing-comma = true
target_version = ["py310", "py311"]

[tool.coverage.run]
source = ["triex"]
omit = ["tests/"]
branch = true

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if log:"
]
fail_under = 100
show_missing = true

[tool.pylint.main]
ignore-paths = ["^(.*/)?.venv/.*$", "^(.*/)?dist/.*$"]
load-plugins = ["pylint.extensions.mccabe"]

[tool.pylint.design]
max-complexity = 15

[tool.pylint.format]
max-line-length = 120

[tool.pylint.imports]
allow-reexport-from-package = true

[tool.pyright]
ignore = [".venv/*", "dist/*"]
pythonVersion = "3.10"
venv = ".venv"
venvPath = "."

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = ["tests"]
markers = []
filterwarnings = ["ignore:::.*pytest_cov*"]
